version: '3'

services:
  container1:
    image: frontend-image
    ports:
      - "8081:8081"
      - "19001:19001"
      - "19002:19002"
    networks:
      - mynetwork
    environment:
      - EXP_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=<<HOST LOCAL IP>>>
    depends_on:
      - container2

  container2:
    image: backend-image
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - mynetwork
  #   depends_on:
  #     - database
      
  # database:
  #   image: mysql:8.0.36
  #   container_name: SPE
  #   ports:
  #     - "127.0.0.1:3307:3306"  # Map port 3306 of the container to port 3306 on the host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "Saurabh123"
  #     MYSQL_DATABASE: "SPE"  # Replace with your actual database name
  #   volumes:
  #     - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql  # Mount the SQL dump file




  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch
    restart: always
    environment:
      - network.host=0.0.0.0
      - http.port=9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Set JVM heap size options
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynetwork
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - /home/saurabh/MTech/sem2/spe/finalproject/SPE_finalProject/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch/elasticsearch.yml:ro,z
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash
    restart: always
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "6000:6000/tcp"
      - "9600:9600"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch

  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
  

volumes:
  elastic_data:
    driver: local



networks:
  mynetwork:
    # driver: bridge