version: '3'

services:
  frontend:
    build:
      context: ./SPE_final/  # Specify the directory containing your frontend Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host
    depends_on:
      - backend  # Frontend service depends on the backend service

  backend:
    build:
      context: ./SPE_flask_backend/  # Specify the directory containing your backend Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 on the host
    depends_on:
      - database  # Backend service depends on the database service

  database:
    image: mysql:8.0.36
    container_name: SPE_db
    ports:
      - "3306:3306"  # Map port 3306 of the container to port 3306 on the host
    environment:
      MYSQL_ROOT_PASSWORD: "Saurabh123"
      MYSQL_DATABASE: "SPE"  # Replace with your actual database name
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql  # Mount the SQL dump file
