version: '3'

services:
  container1:
    image: frontend-image
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - mynetwork
    enviornment:
      - EXP_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - container2

  container2:
    image: backend-image
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - mynetwork
  #   depends_on:
  #     - database
      
  # database:
  #   image: mysql:8.0.36
  #   container_name: SPE
  #   ports:
  #     - "127.0.0.1:3307:3306"  # Map port 3306 of the container to port 3306 on the host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "Saurabh123"
  #     MYSQL_DATABASE: "SPE"  # Replace with your actual database name
  #   volumes:
  #     - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql  # Mount the SQL dump file

networks:
  mynetwork:
