version: '3'

services:
  container1:
    image: frontend-image
    ports:
      - "8081:8081"
      - "19001:19001"
      - "19002:19002"
    networks:
      - mynetwork
    environment:
      - EXP_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=<<HOST LOCAL IP>>>
    depends_on:
      - container2

  container2:
    image: backend-image
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - database
      

  database:
    image: mysql:8
    container_name: SPE_database
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Saurabh123
      - MYSQL_DATABASE=SPE
    volumes:
      - vehiclecount_database:/var/lib/mysql
    command: --bind-address=0.0.0.0
    networks:
      - mynetwork

volumes:
  vehiclecount_database:

networks:
  mynetwork:
    # driver: bridge
